apiVersion: apps/v1
kind: Deployment
metadata:
  name: Event
  labels:
    app: Event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Event
  template:
    metadata:
      labels:
        app: Event
    spec:
      containers:
        - name: Event
          image: username/Event:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5